-- Create office table first (no dependencies)
CREATE TABLE office (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(191) UNIQUE NOT NULL,
  dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create budget table
CREATE TABLE budget (
  id INT PRIMARY KEY AUTO_INCREMENT,
  officeId INT NOT NULL,
  ps DOUBLE NOT NULL,
  mooe DOUBLE NOT NULL,
  co DOUBLE NOT NULL,
  total DOUBLE NOT NULL,
  dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (officeId) REFERENCES office(id) ON DELETE CASCADE
);

-- Create disbursement table
CREATE TABLE disbursement (
  id INT PRIMARY KEY AUTO_INCREMENT,
  dvNo VARCHAR(191) NOT NULL,
  payee VARCHAR(191) NOT NULL,
  officeId INT NOT NULL,
  expenseType VARCHAR(191) NOT NULL,
  expenseCategory VARCHAR(191) NOT NULL,
  amount DOUBLE NOT NULL,
  dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (officeId) REFERENCES office(id) ON DELETE CASCADE
);

-- Create expense table
CREATE TABLE expense (
  id INT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(191) NOT NULL,
  category VARCHAR(191) NOT NULL,
  dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create log table
CREATE TABLE log (
  id INT PRIMARY KEY AUTO_INCREMENT,
  message LONGTEXT NOT NULL,
  type VARCHAR(191) NOT NULL,
  action VARCHAR(191) NOT NULL,
  performedBy VARCHAR(191),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_type_createdAt (type, createdAt)
);

-- Create useradmin table
CREATE TABLE useradmin (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(191) UNIQUE NOT NULL,
  password VARCHAR(191) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);